swagger: '2.0'
info:
  title: amsfunctions.azurewebsites.net
  version: 1.0.0
host: amsfunctions.azurewebsites.net
basePath: /
schemes:
  - https
  - http
paths:
  /api/add-textfile-to-asset:
    post:
      operationId: add-textfile-to-asset
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info
          x-ms-summary: Info
          x-ms-visibility: important
          required: true
          schema:
            type: object
            properties:
              document:
                description: Content of the text file to create
                type: string
                x-ms-summary: Text Content
                x-ms-visibility: important
              fileName:
                description: File name to create
                type: string
                x-ms-summary: File name
                x-ms-visibility: important
              assetId:
                description: Id of the existing asset where to put the file
                type: string
                x-ms-summary: Existing Asset Id
                x-ms-visibility: important
              convertTtml:
                description: Convert the document from ttml to vtt and create another vtt file in the asset
                type: boolean
                x-ms-summary: Convert from ttml to vtt
                x-ms-visibility: optional
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/check-blob-copy-to-asset-status:
    post:
      operationId: check-blob-copy-to-asset-status
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info
          x-ms-summary: Info
          x-ms-visibility: important
          required: true
          schema:
            type: object
            properties:
              destinationContainer:
                description: Destination container
                type: string
                x-ms-summary: Destination container
                x-ms-visibility: important
              delay:
                description: Delay in ms
                type: number
                x-ms-summary: Delay
                x-ms-visibility: optional
              assetStorage:
                description: Name of the attached storage where to create the asset
                type: string
                x-ms-summary: storage name of the asset
                x-ms-visibility: optional
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Copy Status
          schema:
            type: object
            properties:
              copyStatus:
                type: number
                description: Returns copy status (2 as example)
                x-ms-summary: Copy Status
              isRunning:
                type: string
                description: True if job is still running
                x-ms-summary: is Running
              isSuccessful:
                type: string
                description: True if job is a success
                x-ms-summary: is Successful
      security:
        - apikeyQuery: []
  /api/check-blob-copy-to-container-status:
    post:
      operationId: check-blob-copy-to-container-status
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info to check job status
          x-ms-summary: Job ID
          x-ms-visibility: important
          required: true
          schema:
            type: object
            properties:
              targetStorageAccountName:
                description: Target Storage account name
                type: string
                x-ms-summary: Target Storage Account Name
                x-ms-visibility: important
              targetStorageAccountKey:
                description: Target Storage account key
                type: string
                x-ms-summary: target Storage Account Key
                x-ms-visibility: important
              targetContainer:
                description: Target container
                type: string
                x-ms-summary: Target Container
                x-ms-visibility: important
              delay:
                description: Delay in ms
                type: number
                x-ms-summary: Delay
                x-ms-visibility: optional
              fileNamePrefix:
                description: File name prefix (video.mp4 or video)
                type: string
                x-ms-summary: File Name Prefix
                x-ms-visibility: optional
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Copy Status
          schema:
            type: object
            properties:
              copyStatus:
                type: number
                description: Returns copy status (2 as example)
                x-ms-summary: Copy Status
              isRunning:
                type: string
                description: True if job is still running
                x-ms-summary: is Running
              isSuccessful:
                type: string
                description: True if job is a success
                x-ms-summary: is Successful
      security:
        - apikeyQuery: []
  /api/check-job-status:
    post:
      operationId: check-job-status
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info to check job status
          x-ms-summary: Job ID
          x-ms-visibility: important
          required: true
          schema:
            type: object
            properties:
              jobId:
                description: Job ID
                type: string
                x-ms-summary: Job Id
                x-ms-visibility: important
              extendedInfo:
                description: >-
                  optional. Returns ams account unit size, nb units, nb of jobs
                  in queue, scheduled and running states. Only if job is
                  complete or error
                type: boolean
                x-ms-summary: Extended Info
                x-ms-visibility: optional
              noWait:
                description: >-
                  optional. Set this parameter if you don't want the function to
                  wait. Otherwise it waits for 15 seconds if the job is not
                  completed before doing another check and terminate
                type: boolean
                x-ms-summary: noWait
                x-ms-visibility: optional
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Job Status
          x-ms-summary: Job Status
          schema:
            type: object
            properties:
              jobState:
                type: number
                description: Current Job State
                x-ms-summary: Job State
              isRunning:
                type: string
                description: Check if job is currently running
                x-ms-summary: Is Running
              isSuccessful:
                type: string
                description: Was the job successful
                x-ms-summary: Is Successful
              errorText:
                type: string
                description: error(s) text if job state is error
                x-ms-summary: Error Text
              startTime:
                type: string
                x-ms-summary: Start Time
              endTime:
                type: string
                x-ms-summary: End Time
              runningDuration:
                type: number
                x-ms-summary: Running Duration
              progress:
                type: number
                x-ms-summary: Progress
      security:
        - apikeyQuery: []
  /api/check-task-status:
    post:
      operationId: check-task-status
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/create-empty-asset:
    post:
      operationId: create-empty-asset
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/delete-entity:
    post:
      operationId: delete-entity
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/generate-ism-manifest:
    post:
      operationId: generate-ism-manifest
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/list-asset-files:
    post:
      operationId: list-asset-files
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info to check job status
          x-ms-summary: Job ID
          x-ms-visibility: important
          required: true
          schema:
            type: object
            properties:
              assetId:
                description: Asset ID
                type: string
                x-ms-summary: Asset Id
                x-ms-visibility: important
              startsWith:
                type: string
                x-ms-summary: Starts With
                x-ms-visibility: optional
              endsWith:
                type: string
                x-ms-summary: Ends With
                x-ms-visibility: optional
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Job Status
          x-ms-summary: Job Status
          schema:
            type: object
            properties:
              assetFiles:
                type: array
                items:
                  type: string
                description: Current Job State
                x-ms-summary: Job State
      security:
        - apikeyQuery: []
  /api/live-subclip-analytics:
    post:
      operationId: live-subclip-analytics
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info to create a subclip job
          x-ms-summary: Request Body
          x-ms-visibility: important
          required: true
          schema:
            type: string
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
          x-ms-summary: Live Clip
          schema:
            type: object
            properties:
              triggerStart:
                type: string
                description: When the trigger started
                x-ms-summary: Trigger Start
              jobId:
                type: string
                x-ms-summary: Job Id
              channelName:
                type: string
                x-ms-summary: Channel Name
              programId:
                type: string
                x-ms-summary: Program Id
              programName:
                type: string
                x-ms-summary: Program Name
              programUrl:
                type: string
                x-ms-summary: Program Url
              programState:
                type: string
                x-ms-summary: Program State
              programStateChanged:
                type: boolean
                x-ms-summary: Program State Changed
              otherJobsQueue:
                type: number
                x-ms-summary: Other Jobs Queue
              subclip:
                type: object
                properties:
                  assetId:
                    type: string
                    x-ms-summary: Subclp Asset Id
                  taskId:
                    type: string
                    x-ms-summary: Subclp Task Id
                  start:
                    type: string
                    x-ms-summary: Subclp Task Start
                  duration:
                    type: string
                    x-ms-summary: Subclp Duration
              indexV2:
                type: object
                properties:
                  assetId:
                    type: string
                    x-ms-summary: IndexV2 Asset Id
                  taskId:
                    type: string
                    x-ms-summary: IndexV2 Task Id
                  language:
                    type: string
                    x-ms-summary: IndexV2 Language
      security:
        - apikeyQuery: []
  /api/publish-asset:
    post:
      operationId: publish-asset
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info to check job status
          x-ms-summary: Asset Info
          x-ms-visibility: important
          required: true
          schema:
            type: object
            properties:
              assetId:
                description: Asset ID
                type: string
                x-ms-summary: Asset Id
                x-ms-visibility: important
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
          x-ms-summary: Live Clip
          schema:
            type: object
            properties:
              playerUrl:
                description: Url of demo AMP with content
                type: string
                x-ms-summary: Player Url
              smoothUrl:
                type: string
                description: >-
                  Url for the published asset (contains name.ism/manifest at the
                  end) for dynamic packaging
                x-ms-summary: Smooth Url
              pathUrl:
                type: string
                description: Url of the asset (path)
                x-ms-summary: Path Url
      security:
        - apikeyQuery: []
  /api/return-analytics:
    post:
      operationId: return-analytics
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/return-subtitles:
    post:
      operationId: return-subtitles
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Info to check job status
          x-ms-summary: Subtitle info
          x-ms-visibility: important
          required: true
          schema:
            type: object
            properties:
              assetId:
                description: Asset ID
                type: string
                x-ms-summary: Asset Id
                x-ms-visibility: important
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
          x-ms-summary: Live Clip
          schema:
            type: object
            properties:
              vttUrl:
                type: string
                description: the full path to vtt file if asset is published
              ttmlUrl:
                type: string
                description: the full path to vtt file if asset is published
              pathUrl:
                type: string
                description: the path to the asset if asset is published
              vttDocument:
                type: string
                description: 'the full vtt document,'
              vttDocumentOffset:
                type: string
                description: the full vtt document with offset
              ttmlDocument:
                type: string
                description: the full ttml document
              ttmlDocumentOffset:
                type: string
                description: the full ttml document with offset
      security:
        - apikeyQuery: []
  /api/set-media-ru:
    post:
      operationId: set-media-ru
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/start-asset-copy-to-container:
    post:
      operationId: start-asset-copy-to-container
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/start-blob-copy-to-asset:
    post:
      operationId: start-blob-copy-to-asset
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/submit-job:
    post:
      operationId: submit-job
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
  /api/sync-asset:
    post:
      operationId: sync-asset
      produces: []
      consumes: []
      parameters: []
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
definitions: {}
securityDefinitions:
  apikeyQuery:
    type: apiKey
    name: code
    in: query
